sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "8"

services:
  - mongodb

after_success:
  - npm run coveralls

before_script:
  - npm prune
  - npm run install_mock
  - redis-server --daemonize yes

addons:
  apt:
    packages:
      - redis-server
