sudo: false
language: node_js
cache:
  directories:
    - node_modules

before_script:
  - npm prune

node_js:
  - "node"

services:
  - mongodb

after_success:
  - npm run coveralls

before_script:
  - npm run install_mock

addons:
  apt:
    packages:
      - redis-server
