sudo: false
language: node_js
cache:
  directories:
    - node_modules

before_script:
  - npm prune

node_js:
  - "node"

services:
  - redis-server
  - mongodb

after_success:
  - npm run coveralls

after_install:
  - npm run install_mock
